#!/usr/bin/env python

import json
import click
from requests import Response

import secure_requests
import utils
from utils import default_command, logger

def calc_exit_code(res: Response):
    if res.status_code == 200:
        return 0
    
    content = json.loads(res.content)
    message = content['message']

    if 'organizations.name' in message:
        return -1

    return 0

@default_command
@click.argument('organization', required=True, type=str)
@click.argument('username', required=True, type=str)
@click.argument('name', required=True, type=str)
@click.argument('email', required=True, type=str)
@click.argument('pub_key_file', required=True, type=click.Path(exists=True, dir_okay=False))
def rep_create_org(organization: str, username: str, name: str, email: str, pub_key_file: str):
    
    # Load and decrypt the private key
    with open(pub_key_file, 'r') as file:
        keys = json.load(file)
    public_key = keys['REP_PUB_KEY']
    
    body = {
        "organization": organization,
        "username": username,
        "name": name,
        "email": email,
        "public_key": public_key
    }

    res = secure_requests.secure_post(f"http://{utils.state['REP_ADDRESS']}/organization/create", json=body)
    logger.debug(res)
    logger.info(res.content.decode())
    
    return calc_exit_code(res)


if __name__ == '__main__':
    rep_create_org()
