#!/usr/bin/env python

import json
import click
import secure_requests

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.argument('role',required=True, type=str)
def rep_add_subject(session_file:str, role:str):
    
    with open(session_file, 'r') as f:
        session = f.read().strip()


    headers = {
        "session": session
    }

    body = {
        "role": role
    }

    res = secure_requests.secure_post(f"http://{utils.state['REP_ADDRESS']}/role/assume", headers=headers, json=body)

    logger.info(json.loads(res.content))


if __name__ == '__main__':
    rep_add_subject()