#!/usr/bin/env python

import json
from typing import List
import click
import secure_requests

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
def rep_list_roles(session_file:str):
    
    with open(session_file, 'r') as f:
        session = f.read().strip()


    headers = {
        "session": session
    }

    res = secure_requests.secure_get(f"http://{utils.state['REP_ADDRESS']}/role/list", headers=headers)

    if res.status_code != 200:
        logger.info(res.content.decode())
        return -1
    
    # output
    data = json.loads(res.content)
    roles: List[str, bool] = [(i['name'], i['status']) for i in sorted(data['roles'], key=lambda x: -x['status'])]
    
    print("Status     | Name")
    print("-----------------")
    for name, stat in roles:
        status = 'Active' if stat else 'Suspended'
        print(f"{status:<10} | {name:<20}")

    return 0


if __name__ == '__main__':
    rep_list_roles()