#!/usr/bin/env python

import click

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.argument('usename',required=True, type=str)
@click.argument('name',required=True, type=str)
@click.argument('email', required=True, type=str)
@click.argument('cred_file', required=True, type=click.Path(exists=True, dir_okay=False))
def rep_add_subject(session_file:str, username:str, name:str, email:str, cred_file:str):
    with open(session_file, 'r') as f:
        session = f.read().strip()

    headers = {
            "session": session
    }
    
    pass

if __name__ == '__main__':
    rep_add_subject()