#!/usr/bin/env python

import json
from typing import List
import click
import secure_requests

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.argument('role', required=True, type=str)
def rep_suspend_role(session_file: str, role: str):
    
    with open(session_file, 'r') as f:
        session = f.read().strip()

    headers = {
        "session": session
    }

    body = {
        "role": role,
        "status": False
    }

    res = secure_requests.secure_put(f"http://{utils.state['REP_ADDRESS']}/role/status", headers=headers, json=body)

    if res.status_code != 200:
        logger.info(res.content.decode())
        return
    
    # output
    data = json.loads(res.content)
    logger.info(data['message'])


if __name__ == '__main__':
    rep_suspend_role()