#!/usr/bin/env python

import click
import requests

import utils
from utils import default_command, logger

@default_command
@click.argument('organization', required=True, type=str)
@click.argument('username', required=True, type=str)
@click.argument('name', required=True, type=str)
@click.argument('email', required=True, type=str)
@click.argument('pub_key_file', required=True, type=click.Path(exists=True, dir_okay=False))
def rep_create_org(organization: str, username: str, name: str, email: str, pub_key_file: str):
    
    # read public key
    with open(pub_key_file, 'r') as file:
        public_key = file.read()
    
    body = {
        "organization": organization,
        "username": username,
        "name": name,
        "email": email,
        "public_key": public_key
    }

    res = requests.post(f"http://{utils.state['REP_ADDRESS']}/organization/create", json=body)
    logger.debug(res)
    logger.info(res.content.decode())
    exit(0)


if __name__ == '__main__':
    rep_create_org()
