#!/usr/bin/env python

import json
from typing import List
import click
import secure_requests

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.argument('permission', required=True, type=str)
def rep_list_permission_roles(session_file: str, permission: str):

    with open(session_file, 'r') as f:
        session = f.read().strip()

    headers = {
        "session": session
    }

    body = {
        'permission': permission
    }
    
    res = secure_requests.secure_get(
        f"http://{utils.state['REP_ADDRESS']}/role/list_permission_roles",
        headers=headers,
        params=body
    )

    if res.status_code != 200:
        logger.info(res.content.decode())
        return

    # output
    data = json.loads(res.content)
    roles: List[str, bool] = [(i['name'], i['status']) for i in sorted(data['roles'], key=lambda x: -x['status'])]
    
    print("Status     | Name")
    print("-----------------")
    for name, stat in roles:
        status = 'Active' if stat else 'Suspended'
        print(f"{status:<10} | {name:<20}")



if __name__ == '__main__':
    rep_list_permission_roles()