#!/usr/bin/env python

import click
import requests

import utils
from utils import default_command, logger

@default_command
@click.argument('file_handle', required=True, type=str)
@click.argument('file', required=False, type=click.Path(exists=False))
def rep_get_file(file_handle: str, file: str):
    
    # Send the GET request to download the file
    url = f"http://{utils.state['REP_ADDRESS']}/file/download/{file_handle}"
    response = requests.get(url)

    # Check if the file exists on the server
    if response.status_code != 200:
        logger.info("Failed to download file:", response.json())
        return
    
    # output
    logger.info(f"File {file_handle} downloaded successfully.")
    if file is None:
        print(response.content.decode())
        return
    
    with open(file, '+wb') as f:
        f.write(response.content)
    

if __name__ == '__main__':
    rep_get_file()