#!/usr/bin/env python

import json
from typing import List
import click
import secure_requests

import utils
from utils import default_command, logger

@default_command
@click.argument('session_file', required=True, type=click.Path(exists=True, dir_okay=False))
@click.argument('role', required=True, type=str)
def rep_list_role_permissions(session_file: str, role: str):

    with open(session_file, 'r') as f:
        session = f.read().strip()

    headers = {
        "session": session
    }

    body = {
        'role': role
    }
    
    res = secure_requests.secure_get(
        f"http://{utils.state['REP_ADDRESS']}/role/list_permissions",
        headers=headers,
        params=body
    )

    if res.status_code != 200:
        logger.info(res.content.decode())
        return -1

    # output
    data = json.loads(res.content)
    roles: List[str] = data['permissions']
    
    print(f"'{role}' permissions:")
    for perm in roles:
        print("\t"+perm)
    
    return 0



if __name__ == '__main__':
    rep_list_role_permissions()